name: Publish docs on GH Pages

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'
  workflow_dispatch:
  workflow_call:

jobs:
  generate-and-publish:
    runs-on: ubuntu-22.04
    steps:

     - uses: actions/checkout@v4.1.1
       with:
        fetch-depth: 0
        token: ${{ secrets.DEPLOYMENT_TOKEN }}
     - name: Generate API documentation
       with:
         token: ${{ secrets.DEPLOYMENT_TOKEN }}
       run: |
         VERSION=$(git tag --sort=committerdate | tail -1)
         echo Generating API documentation for version $VERSION
         ./gradlew -Pversion=$VERSION dokkaHtml

     - uses: JamesIves/github-pages-deploy-action@v4
       name: Publish API documentation
       with:
         token: ${{ secrets.DEPLOYMENT_TOKEN }}
         branch: gh-pages
         folder: build/dokka/html
         target-folder: ./


