name: Publish docs on GH Pages

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'
  workflow_dispatch:
  workflow_call:

jobs:
  generate-and-publish:
    runs-on: ubuntu-22.04
    steps:

     - uses: actions/checkout@v4.1.1
       with:
        fetch-depth: 0
        token: ${{ secrets.DEPLOYMENT_TOKEN }}


     - name: Generate API documentation

       run: |
         echo Generating API documentation
         ./gradlew dokkaHtml

     - uses: JamesIves/github-pages-deploy-action@v4
       name: Publish API documentation
       with:
         token: ${{ secrets.DEPLOYMENT_TOKEN }}
         branch: gh-pages
         folder: build/dokka/html
         target-folder: ./


